name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    # Run each command in parallel with the same setup steps.
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        config:
          # Specify names so that the GitHub branch protection settings for
          # required checks don't need to change if we ever change the commands used.
          - name: lint
            command: |
              # lint steps
              set -x
              yarn license-check
              yarn dedupe --check
              yarn run tsc --noEmit # typecheck files that are not included by webpack or package builds
              yarn run lint:ci
              yarn run lint:unused-exports
          - name: packages
            command: yarn run build:packages
          - name: web
            command: yarn run web:build:prod
          - name: test
            command: yarn run test --maxWorkers=100%
          - name: pack studio-base
            command: yarn workspace @foxglove/studio-base pack
        include:
          - os: windows-2019
            config:
              name: packages
              command: echo complete

    name: ${{ matrix.config.name }} (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v5-${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - run: ${{ matrix.config.command }}

  storybook:
    runs-on: ubuntu-20.04

    name: storybook (ubuntu-20.04)

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # - name: Restore cache
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       .yarn/cache
      #       **/node_modules
      #     key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: v5-${{ runner.os }}-yarn-

      # - run: yarn install --immutable

      # - run: yarn workspace @foxglove/studio-base run build-storybook

      - uses: hmarr/debug-action@v2 # FIXME

      - run: echo ${{ github.event.repository.full_name }}
      - run: echo ${{ github.event.pull_request.base.repo.full_name }}

      - uses: chromaui/action@v1
        if: ${{ github.event.repository.full_name == 'foxglove/studio' || github.event.pull_request.base.repo.full_name == 'foxglove/studio' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # FIXME
          projectToken: f50040a29fb8
          storybookBuildDir: packages/studio-base/storybook-static
          # autoAcceptChanges: main
          exitOnceUploaded: true

  integration:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    name: integration (${{ matrix.os }})

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            **/node_modules
          key: v5-${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: v5-${{ runner.os }}-yarn-

      - run: yarn install --immutable

      - name: test:integration
        if: matrix.os == 'ubuntu-20.04'
        uses: GabrielBB/xvfb-action@v1.5
        with:
          working-directory: ./
          run: yarn run test:integration

      - name: test:integration
        if: matrix.os != 'ubuntu-20.04'
        run: yarn run test:integration
