# Deploy runs in a separate workflow so it can access repository secrets.
# Don't execute any untrusted code here!
name: Deploy

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Download
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "studio-web"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/studio-web.zip`, Buffer.from(download.data));

      - run: unzip -d public studio-web.zip

      - run: echo '${{ toJSON(github.event.workflow_run) }}'

      - uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ github.token }}
          branch: ${{ github.event.workflow_run.head_ref || github.event.workflow_run.ref_name }}
          projectName: foxglove-studio
          directory: public
